---
- name: install apache and upload my web page
  hosts: all
  become: yes

  vars:
   source_file: ./index.html
   destin_file: /var/www/html
  
  tasks:
#  - name: Install apache web server
#    apt: name=apache2 state=latest
  
  - name: Copy MyHomePage to Servers
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart apache    

  - name: start websever and make it enable on boot
    service: name=apache2 state=started enabled=yes
  
  
  handlers:
  - name: Restart apache
    service: name=apache2 state=restarted
